language: c
sudo: false
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib
    - libogg-dev
    - libvorbis-dev
    - ffmpeg

before_install:
  - git clone https://github.com/savonet/ocaml-ogg.git
  - cd ocaml-ogg && git submodule init && git submodule update && ./bootstrap && ./configure && make && cd ..

script: ./bootstrap && ./configure --with-ogg-dir=ocaml-ogg/src && make && make -C examples && make test
